# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maxtercubex/Descargas/is/re-uco-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maxtercubex/Descargas/is/re-uco-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxtercubex/Descargas/is/re-uco-main/CMakeFiles /home/maxtercubex/Descargas/is/re-uco-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxtercubex/Descargas/is/re-uco-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main2

# Build rule for target.
main2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main2
.PHONY : main2

# fast build rule for target.
main2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/build
.PHONY : main2/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

common/date.o: common/date.cpp.o

.PHONY : common/date.o

# target to build an object file
common/date.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/common/date.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/common/date.cpp.o
.PHONY : common/date.cpp.o

common/date.i: common/date.cpp.i

.PHONY : common/date.i

# target to preprocess a source file
common/date.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/common/date.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/common/date.cpp.i
.PHONY : common/date.cpp.i

common/date.s: common/date.cpp.s

.PHONY : common/date.s

# target to generate assembly for a file
common/date.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/common/date.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/common/date.cpp.s
.PHONY : common/date.cpp.s

dto/maquina.o: dto/maquina.cpp.o

.PHONY : dto/maquina.o

# target to build an object file
dto/maquina.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/dto/maquina.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dto/maquina.cpp.o
.PHONY : dto/maquina.cpp.o

dto/maquina.i: dto/maquina.cpp.i

.PHONY : dto/maquina.i

# target to preprocess a source file
dto/maquina.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/dto/maquina.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dto/maquina.cpp.i
.PHONY : dto/maquina.cpp.i

dto/maquina.s: dto/maquina.cpp.s

.PHONY : dto/maquina.s

# target to generate assembly for a file
dto/maquina.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/dto/maquina.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dto/maquina.cpp.s
.PHONY : dto/maquina.cpp.s

dto/reserva.o: dto/reserva.cpp.o

.PHONY : dto/reserva.o

# target to build an object file
dto/reserva.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/dto/reserva.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dto/reserva.cpp.o
.PHONY : dto/reserva.cpp.o

dto/reserva.i: dto/reserva.cpp.i

.PHONY : dto/reserva.i

# target to preprocess a source file
dto/reserva.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/dto/reserva.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dto/reserva.cpp.i
.PHONY : dto/reserva.cpp.i

dto/reserva.s: dto/reserva.cpp.s

.PHONY : dto/reserva.s

# target to generate assembly for a file
dto/reserva.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/dto/reserva.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dto/reserva.cpp.s
.PHONY : dto/reserva.cpp.s

dto/usuario.o: dto/usuario.cpp.o

.PHONY : dto/usuario.o

# target to build an object file
dto/usuario.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/dto/usuario.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dto/usuario.cpp.o
.PHONY : dto/usuario.cpp.o

dto/usuario.i: dto/usuario.cpp.i

.PHONY : dto/usuario.i

# target to preprocess a source file
dto/usuario.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/dto/usuario.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dto/usuario.cpp.i
.PHONY : dto/usuario.cpp.i

dto/usuario.s: dto/usuario.cpp.s

.PHONY : dto/usuario.s

# target to generate assembly for a file
dto/usuario.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/dto/usuario.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dto/usuario.cpp.s
.PHONY : dto/usuario.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

models/MaquinaModel.o: models/MaquinaModel.cpp.o

.PHONY : models/MaquinaModel.o

# target to build an object file
models/MaquinaModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/models/MaquinaModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/models/MaquinaModel.cpp.o
.PHONY : models/MaquinaModel.cpp.o

models/MaquinaModel.i: models/MaquinaModel.cpp.i

.PHONY : models/MaquinaModel.i

# target to preprocess a source file
models/MaquinaModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/models/MaquinaModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/models/MaquinaModel.cpp.i
.PHONY : models/MaquinaModel.cpp.i

models/MaquinaModel.s: models/MaquinaModel.cpp.s

.PHONY : models/MaquinaModel.s

# target to generate assembly for a file
models/MaquinaModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/models/MaquinaModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/models/MaquinaModel.cpp.s
.PHONY : models/MaquinaModel.cpp.s

models/ReservaModel.o: models/ReservaModel.cpp.o

.PHONY : models/ReservaModel.o

# target to build an object file
models/ReservaModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/models/ReservaModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/models/ReservaModel.cpp.o
.PHONY : models/ReservaModel.cpp.o

models/ReservaModel.i: models/ReservaModel.cpp.i

.PHONY : models/ReservaModel.i

# target to preprocess a source file
models/ReservaModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/models/ReservaModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/models/ReservaModel.cpp.i
.PHONY : models/ReservaModel.cpp.i

models/ReservaModel.s: models/ReservaModel.cpp.s

.PHONY : models/ReservaModel.s

# target to generate assembly for a file
models/ReservaModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/models/ReservaModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/models/ReservaModel.cpp.s
.PHONY : models/ReservaModel.cpp.s

models/UsuarioModel.o: models/UsuarioModel.cpp.o

.PHONY : models/UsuarioModel.o

# target to build an object file
models/UsuarioModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/models/UsuarioModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/models/UsuarioModel.cpp.o
.PHONY : models/UsuarioModel.cpp.o

models/UsuarioModel.i: models/UsuarioModel.cpp.i

.PHONY : models/UsuarioModel.i

# target to preprocess a source file
models/UsuarioModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/models/UsuarioModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/models/UsuarioModel.cpp.i
.PHONY : models/UsuarioModel.cpp.i

models/UsuarioModel.s: models/UsuarioModel.cpp.s

.PHONY : models/UsuarioModel.s

# target to generate assembly for a file
models/UsuarioModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/models/UsuarioModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/models/UsuarioModel.cpp.s
.PHONY : models/UsuarioModel.cpp.s

tests.o: tests.cpp.o

.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i

.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s

.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... main2"
	@echo "... common/date.o"
	@echo "... common/date.i"
	@echo "... common/date.s"
	@echo "... dto/maquina.o"
	@echo "... dto/maquina.i"
	@echo "... dto/maquina.s"
	@echo "... dto/reserva.o"
	@echo "... dto/reserva.i"
	@echo "... dto/reserva.s"
	@echo "... dto/usuario.o"
	@echo "... dto/usuario.i"
	@echo "... dto/usuario.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... models/MaquinaModel.o"
	@echo "... models/MaquinaModel.i"
	@echo "... models/MaquinaModel.s"
	@echo "... models/ReservaModel.o"
	@echo "... models/ReservaModel.i"
	@echo "... models/ReservaModel.s"
	@echo "... models/UsuarioModel.o"
	@echo "... models/UsuarioModel.i"
	@echo "... models/UsuarioModel.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

